name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ['1.21', '1.22']

      - name: Run tests
        run: go test ./...

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./... > benchmark.txt

      - name: Benchmark summary
        run: |
          echo "## Benchmark Summary" >> $GITHUB_STEP_SUMMARY
          grep -E '^Benchmark' benchmark.txt >> $GITHUB_STEP_SUMMARY
